# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-svc-c
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer

